Список из задания 1:
1. Матрица смежности
2. Матрица инцидентности
3. Список смежности
4. Список дуг
5. Упорядоченный список дуг

Задание 2. Запрограммировать представления из заданий 1а-г (в виде одно- или многомерных массивов, словарей и т. д.). Можно использовать Python (numpy), C/C++.

In [1]:
import numpy as np

In [2]:
mat_smezh = np.array([
    [0, 1, 1, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [0, 0, 0, 0]
])

print("Матрица смежности:")
print(mat_smezh)

Матрица смежности:
[[0 1 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [3]:
mat_inc = np.array([
    [-1, -1,  0,  0],
    [ 1,  0, -1,  0],
    [ 0,  1,  1, -1],
    [ 0,  0,  0,  1]
])

print("Матрица инцидентности:")
print(mat_inc)

Матрица инцидентности:
[[-1 -1  0  0]
 [ 1  0 -1  0]
 [ 0  1  1 -1]
 [ 0  0  0  1]]


In [ ]:
spisok_smezh = {
    0: [1, 2],
    1: [2],
    2: [3],
    3: []
}

print("Список смежности:")
print(spisok_smezh)

In [4]:
spisok_dug = [
    (0, 1),
    (0, 2),
    (1, 2),
    (2, 3)
]

print("Список дуг:")
print(spisok_dug)

Список дуг:
[(0, 1), (0, 2), (1, 2), (2, 3)]


In [5]:
upоряд_dug = sorted(spisok_dug)

print("Упорядоченный список дуг:")
print(upоряд_dug)

Упорядоченный список дуг:
[(0, 1), (0, 2), (1, 2), (2, 3)]


Задание 3. Написать функцию для просмотра дуг, исходящих из данной вершины. В качестве аргументов: граф (может быть в различных представлениях), название представления графа (матрица смежности, матрица инцидентности, список смежности, список дуг, упорядоченный список дуг), номер вершины. На выходе: список кортежей вида (i, j), где i - вершина, из которой выходит дуга, j - вершина, в которую входит дуга).

In [6]:
def ishod_dugi(graph, vid, vershina):
    otvet = []
    if vid == "матрица смежности":
        for j in range(len(graph[vershina])):
            if graph[vershina][j] == 1:
                otvet.append((vershina, j))
    elif vid == "матрица инцидентности":
        stroki = len(graph)
        stolbцы = len(graph[0])
        for e in range(stolbцы):
            start = -1
            end = -1
            for v in range(stroki):
                if graph[v][e] == -1:
                    start = v
                if graph[v][e] == 1:
                    end = v
            if start == vershina:
                otvet.append((start, end))
    elif vid == "список смежности":
        for kuda in graph[vershina]:
            otvet.append((vershina, kuda))
    elif vid == "список дуг":
        for дуга in graph:
            if дуга[0] == vershina:
                otvet.append(дуга)
    elif vid == "упорядоченный список дуг":
        for дуга in graph:
            if дуга[0] == vershina:
                otvet.append(дуга)
    return otvet

Задание 4. Написать функцию для перевода графа из одного представления в другое. Аргументы функции: граф, название начального представления графа, название требуемого представления графа (кроме упорядоченного списка дуг). Функция должна вернуть граф в требуемом представлении.

In [7]:
def perevod(graph, start_vid, new_vid):
    dugi = []

    # Матрица смежности
    if start_vid == "матрица смежности":
        n = len(graph)
        for i in range(n):
            for j in range(n):
                if graph[i][j] == 1:
                    dugi.append((i, j))

    # Матрица инцидентности
    elif start_vid == "матрица инцидентности":
        stroki = len(graph)
        stolbцы = len(graph[0])
        for e in range(stolbцы):
            start = -1
            end = -1
            for v in range(stroki):
                if graph[v][e] == -1:
                    start = v
                if graph[v][e] == 1:
                    end = v
            dugi.append((start, end))

    # Список смежности
    elif start_vid == "список смежности":
        for v in graph:
            for kuda in graph[v]:
                dugi.append((v, kuda))

    # Список дуг
    elif start_vid == "список дуг":
        dugi = graph.copy()

    # Упорядоченный список дуг
    elif start_vid == "упорядоченный список дуг":
        dugi = graph.copy()

    # Список дуг
    if new_vid == "список дуг":
        return dugi
    elif new_vid == "матрица смежности":
        max_v = 0
        for u, v in dugi:
            max_v = max(max_v, u, v)
        n = max_v + 1
        mat = np.zeros((n, n), dtype=int)
        for u, v in dugi:
            mat[u][v] = 1
        return mat
    elif new_vid == "матрица инцидентности":
        max_v = 0
        for u, v in dugi:
            max_v = max(max_v, u, v)
        n = max_v + 1
        m = len(dugi)
        mat = np.zeros((n, m), dtype=int)
        for e, (u, v) in enumerate(dugi):
            mat[u][e] = -1
            mat[v][e] = 1
        return mat
    elif new_vid == "список смежности":
        max_v = 0
        for u, v in dugi:
            max_v = max(max_v, u, v)
        n = max_v + 1
        spisok = {}
        for i in range(n):
            spisok[i] = []
        for u, v in dugi:
            spisok[u].append(v)
        return spisok

test

In [8]:
print("Исходящие дуги из вершины 0:")
print(ishod_dugi(mat_smezh,
                 "матрица смежности",
                 0))
print("Перевод списка дуг в матрицу смежности:")
nov_mat = perevod(spisok_dug,
                  "список дуг",
                  "матрица смежности")
print(nov_mat)
print("Перевод матрицы смежности в список смежности:")
nov_spisok = perevod(mat_smezh,
                     "матрица смежности",
                     "список смежности")
print(nov_spisok)

Исходящие дуги из вершины 0:
[(0, 1), (0, 2)]
Перевод списка дуг в матрицу смежности:
[[0 1 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
Перевод матрицы смежности в список смежности:
{0: [1, 2], 1: [2], 2: [3], 3: []}
